# Generated by Django 5.1 on 2024-09-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_atividade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atividade',
        ),
    ]
