# Generated by Django 5.1 on 2024-09-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='venceu',
            field=models.BooleanField(),
        ),
    ]
