# Generated by Django 5.1 on 2024-09-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_jogo_venceu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jogo',
        ),
    ]
