# Generated by Django 5.1 on 2024-09-10 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_jogo_delete_atividadealuno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jogo',
        ),
    ]
