# Generated by Django 5.1 on 2024-09-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='resultado',
            field=models.CharField(default='Pendente', max_length=100),
        ),
    ]
