# Generated by Django 5.1 on 2024-09-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_atividade_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='resultado',
            field=models.CharField(choices=[('vitoria', 'Vitória'), ('derrota', 'Derrota')], max_length=20),
        ),
    ]
